<?php

// Generated by Haxe 3.4.2
class controllers_AuthController {
	public function __construct(){}
	static function dispatch($request) {
		if($request->method === "GET") {
			controllers_AuthController::connection($request);
		} else {
			$request->setReturnCode(406, "Not Acceptable\x0Amissing reference");
		}
	}
	static function connection($request) {
		$request->setHeader("Content-Type", "application/json");
		$request->send(haxe_Json::phpJsonEncode(models_Connexion::auth($request), null, null));
	}
	function __toString() { return 'controllers.AuthController'; }
}
