<?php

// Generated by Haxe 3.4.2
class models_Helped {
	public function __construct(){}
	static function auth($request) {
		$cookies = $request->cookies;
		$login = $cookies->get("login");
		$password = $cookies->get("password");
		$users = Lambda::harray(models_User::$manager->all(null));
		{
			$_g = 0;
			while($_g < $users->length) {
				$u = $users[$_g];
				$_g = $_g + 1;
				$tmp = null;
				if($u->login === $login) {
					$tmp = $u->password === $password;
				} else {
					$tmp = false;
				}
				if($tmp) {
					return $u;
				}
				unset($u,$tmp);
			}
		}
		return null;
	}
	static function admin($request) {
		$u = models_Helped::auth($request);
		$tmp = null;
		if($u !== null) {
			$tmp = $u->login === "admin";
		} else {
			$tmp = false;
		}
		if($tmp) {
			return true;
		} else {
			return false;
		}
	}
	static function himself($request, $user) {
		$u = models_Helped::auth($request);
		$tmp = null;
		if($u !== null) {
			$tmp = $u->idUser === $user->idUser;
		} else {
			$tmp = false;
		}
		if($tmp) {
			return true;
		} else {
			return false;
		}
	}
	function __toString() { return 'models.Helped'; }
}
