<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class models_Offer extends sys_db_Object {
	public function __construct($dte = null, $day = null, $isFrom, $hour, $city, $km, $user) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->idOffer = api_UUID::genUUID();
		$this->dte = $dte;
		$this->day = $day;
		$this->isFrom = $isFrom;
		$this->hour = $hour;
		$this->city = $city;
		$this->km = $km;
		$this->set_user($user);
	}}
	public $idOffer;
	public $dte;
	public $day;
	public $isFrom;
	public $hour;
	public $city;
	public $km;
	public $user;
	public function get_user() {
		return models_User::$manager->h__get($this, "user", "idUser", false);
	}
	public function set_user($_v) {
		return models_User::$manager->h__set($this, "user", "idUser", $_v);
	}
	public $idUser;
	public function __getManager() {
		return models_Offer::$manager;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static $manager;
	static $__properties__ = array("set_user" => "set_user","get_user" => "get_user");
	function __toString() { return 'models.Offer'; }
}
models_Offer::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array("oy4:namey5:Offery7:indexesahy9:relationsaoy6:moduley11:models.Usery4:lockfy4:propy4:usery4:typeR5y7:cascadefy6:isNullfy3:keyy6:idUserghy7:hfieldsby4:cityoR0R15R11fy1:tjy17:sys.db.RecordType:9:1i100gR13oR0R13R11fR16jR17:9:1i36gy2:kmoR0R18R11fR16jR17:3:0gy3:dayoR0R19R11fR16jR17:24:0gy4:houroR0R20R11fR16jR17:9:1i8gy6:isFromoR0R21R11fR16jR17:8:0gy7:idOfferoR0R22R11fR16jR17:9:1i36gy3:dteoR0R23R11fR16jR17:9:1i10ghR12aR22hy6:fieldsar17r19r11r15r13r5r9r7hg")))))));
models_Offer::$manager = new sys_db_Manager(_hx_qtype("models.Offer"));
