<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
class models_User extends sys_db_Object {
	public function __construct($idUser = null, $lastname, $firstname, $email, $phone, $login, $password) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->lastname = $lastname;
		$this->firstname = $firstname;
		$this->email = $email;
		$this->phone = $phone;
		$this->login = $login;
		$this->password = $password;
		if($idUser === null) {
			$this->idUser = api_UUID::genUUID();
		} else {
			$this->idUser = $idUser;
		}
	}}
	public $idUser;
	public $lastname;
	public $firstname;
	public $email;
	public $phone;
	public $login;
	public $password;
	public function __getManager() {
		return models_User::$manager;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static $manager;
	function __toString() { return 'models.User'; }
}
models_User::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array("oy4:namey4:Usery7:indexesahy9:relationsahy7:hfieldsby6:idUseroR0R5y6:isNullfy1:tjy17:sys.db.RecordType:9:1i36gy8:lastnameoR0R9R6fR7jR8:9:1i40gy9:firstnameoR0R10R6fR7jR8:9:1i40gy5:loginoR0R11R6fR7jR8:9:1i40gy5:phoneoR0R12R6fR7jR8:9:1i10gy5:emailoR0R13R6fR7jR8:9:1i100gy8:passwordoR0R14R6fR7jR8:9:1i64ghy3:keyaR5hy6:fieldsar4r6r8r14r12r10r16hg")))))));
models_User::$manager = new sys_db_Manager(_hx_qtype("models.User"));
