<?php

// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
interface sys_db_Connection {
	function request($s);
	function quote($s);
	function addValue($s, $v);
	function lastInsertId();
	function dbName();
}
